### ISSUE TITLE
Release Timeline?

### ISSUE THREAD

**Issue by johnc1231** [Illumina/Nirvana#10]
Not really an "issue", but I didn't quite know the place to put it. It's been a few months since there has been a Nirvana update here. Is there any expected timeline for the next public release?

**Comment by MichaelStromberg** [comment]
Hi John,

Thanks for the reminder! We have now released Nirvana 1.6.2!

The only aspect that is still remaining is the JSON schema documentation. We'll push those to the wiki tomorrow.

Best regards,
// Michael

**Comment by johnc1231** [comment]
Awesome thanks. If you could comment here when the schema docs go up, that'd be great.

**Comment by MichaelStromberg** [comment]
Hi John,

All the documentation has been uploaded now to our [Design Documents](https://github.com/Illumina/Nirvana/wiki/Design-Documents) page.

Enjoy!

// Michael
