### ISSUE TITLE
SpliceAI data missing from Supplementary Annotations

### ISSUE THREAD

**Issue by kmurphy902** [Illumina/Nirvana#105]
The SpliceAI data seems to be missing from the download (see attached log from running this morning). The command I used was:

```
dotnet --roll-forward Major bin/Release/net6.0/Downloader.dll --ga both -o Data
```

[nirvana_download_both_log.txt](https://github.com/Illumina/Nirvana/files/11533952/nirvana_download_both_log.txt)

I have also confirmed that SpliceAI scores are not in the output json.

**Comment by rajatshuvro** [comment]
Hi @kmurphy902 , 
SpliceAI is not available for the open source user. I am sorry for the inconvenience.

Best
