### ISSUE TITLE
unable to find COSMIC annotations in the output json file

### ISSUE THREAD

**Issue by GH-MStamboulian** [Illumina/Nirvana#119]
Hi All im new to Nirvana and used it to annotated a VCF, I did not specify any of the annotation sources when running Nirvana over an input VCF file, and I could not find any information about the COSMIC annotations in the output. furthermore when I also specify COSMIC using the -s argument the script is erroring out and not recognizing the -s argument.

Do you know if Nirvana supports COSMIC ?

**Comment by rajatshuvro** [comment]
@GH-MStamboulian,
The Nirvana project is no longer active. We are working on a replacement from Illumina. Please share your contacts and we will get back to you when the release is ready.

Thanks
Rajat

**Comment by GH-MStamboulian** [comment]
hi @rajatshuvro thanks so much for getting back to me! my email is mstamboulian@guardanthealth.com
