### ISSUE TITLE
JSON output file format: plans to add gnomAD?

### ISSUE THREAD

**Issue by WestleyASherman** [Illumina/Nirvana#12]
Thanks for developing Nirvana and making it publicly available! The JSON output format is great - very well designed. We use the Nirvana JSON format internally in our NGS variant visualization software - either loading the Nirvana JSON format directly or parsing Ensembl VEP annotated VCF files to then populate the Nirvana JSON format.

Since the Ensembl VEP is now providing gnomAD variant frequencies in addition to ExAC variant frequencies, we're planning to populate our Nirvana JSON with the gnomAD variant frequencies. And it would be very cool if we could choose the same keys / field names that the official Nirvana JSON format will eventually use.

Have there, by any chance, already been any decisions on what the Nirvana JSON output format will look like for supporting the gnomAD variant frequencies (i.e. ExAC is just "exac" so maybe gnomAD will be "gnomad")?

**Comment by MichaelStromberg** [comment]
Hi Westley!

The good news is that we've already added and implemented gnomAD in the development team, but we haven't finished the testing process. We're currently using the latest and greatest, gnomAD 2.0.2, which offered improved filtering over the initial release.

Our intention is to have the testing wrapped up in the next two-week period. I'll send you an update here when we've published the new supplementary data set.

Best regards,

// Michael

**Comment by WestleyASherman** [comment]
Thanks for the update on Nirvana using the latest and greatest gnomAD 2.0.2. Nirvana continues to impress with it's pervasive quality! I'll be looking forward to your update when you've published the new supplementary data set.

**Comment by MichaelStromberg** [comment]
Hi Westley,

Testing gnomAD took longer than anticipated, but now everything is working extremely well. We have now included gnomAD WGS and exomes in the latest version of Nirvana (2.0.3). As a result, the supplementary database files are twice as large as before.

When you have time, feel free to take the new version for a test drive. Let us know if you have any issues or other feature requests!

**Comment by WestleyASherman** [comment]
That's very cool and impressive that Nirvana now includes the WGS gnomAD frequencies. I'll look forward to trying it out very soon.
