### ISSUE TITLE
RefSeq annotation GRCh37 transcripts NM not showing latest version

### ISSUE THREAD

**Issue by danlesperance-pki** [Illumina/Nirvana#123]
We have vcf's we annotated with snpEff and received NM numbers with NM######.4; whereas when using Nirvana only the NM######.2 and NM#######.3 are showing up.  Note that we are utilizing GRCh37 and perhaps Nirvana stopped pulling the latest transcripts for Refseq on GRCh37 but wanted to reach out for clarification why this may be the case.

**Comment by rajatshuvro** [comment]
Hello @danlesperance-pki, 
Please note that this tool is no longer being maintained. We have launched Illumina Connected Annotations built based on Nirvana. Please see: https://illumina.github.io/IlluminaConnectedAnnotationsDocumentation/ for details.

Thanks
