### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by veronicatozzo** [Illumina/Nirvana#125]
Hi there, I am following the Getting started tutorial and I am encountering an issue. Everything goes smoothly up to the test instruction 

```
dotnet bin/Release/net6.0/Nirvana.dll \
     -c Data/Cache/GRCh38 \
     --sd Data/SupplementaryAnnotation/GRCh38 \
     -r Data/References/Homo_sapiens.GRCh38.Nirvana.dat \
     -i HiSeq.10000.vcf.gz \
     -o HiSeq.10000
```

which output is

```
   ---------------------------------------------------------------------------
Nirvana                                             (c) 2022 Illumina, Inc.
Stromberg, Roy, Platzer, Siddiqui, Ouyang, et al                     3.18.1
---------------------------------------------------------------------------

Initialization                                         Time     Positions/s
---------------------------------------------------------------------------
Illegal instruction: 4
```
  
 I've tried to start from the source code as well as from the binaries and I reach the same point with both.  Following the installation via Docker is also a dead end, at the same point, it gets stuck for hours without producing any result or error code. 
  
  I am working with macOS 13.6 M2 Chip x86-x64, dotnet 6.0.26. 
  
  Any idea how to fix this?
  Thank you!

**Comment by egidijusz** [comment]
I have the same issue.

OS: Ubuntu 22.04
CPU: Intel Xeon X5650

.NET version 6.0.127

**Comment by schreyers** [comment]
If this helps, this can be added to bypass the AVX usage: https://github.com/Illumina/BlockCompression.

I had this fix and it got to the next step, but got a new / same error after. Issue raised is this: https://github.com/Illumina/Nirvana/issues/128

**Comment by rajatshuvro** [comment]
Please note that this tool is no longer being maintained. We have launched Illumina Connected Annotations built based on Nirvana. Please see: https://illumina.github.io/IlluminaConnectedAnnotationsDocumentation/ for details.
