### ISSUE TITLE
How to access Jasix

### ISSUE THREAD

**Issue by vajanishant** [Illumina/Nirvana#126]
Hello guys,

I was trying to run this:
`sudo docker run --rm -it -v Data:/scratch annotation/nirvana:3.14 dotnet bin/Release/net6.0/Jasix.dll -i dragen.json.gz -q chr1:942450-942455`

But it is throwing an error: 
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

I also generated a file json and jsi files: HiSeq.json.gz.jsi, HiSeq.json.gz

But how can I access HiSeq.json.gz.jsi this file? There's not way to convert this to json or something that should be visible in human readable format?

I'm using gitpod to execute Nirvana via docker.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

I've installed dotnet: 
```
sudo apt-get update &&   sudo apt-get install -y dotnet-sdk-6.0
dotnet --version
6.0.127
```

Please guide me here so that I can get the jsi file in json format or can be able to generate Jasix and can read it in human readable format.

Thanks in advance.

**Comment by rajatshuvro** [comment]
Hi @vajanishant ,
Unfortunately, Nirvana is no longer public. Please follow the instructions here https://illumina.github.io/NirvanaDocumentation/ to get the latest version. 

Best
Rajat
