### ISSUE TITLE
Jasix output not in bgzip format

### ISSUE THREAD

**Issue by frahimov** [Illumina/Nirvana#127]
Hello, the Documentation mentions that "The default output stream is Console. However, if an output filename is provided, Jasix outputs the results to that file in a bgzip compressed format". The annotation file that was provided to me is in a gzip compressed format. I extracted a section of this file with Jasix and wrote the output to a file. But the file is not in a bgzip format. It is just a text file.

**Comment by schreyers** [comment]
@frahimov Did you get an error like this when you setup? (https://github.com/Illumina/Nirvana/issues/128)

Just wondering to see if I am doing something wrong when running the test files

Thanks

**Comment by rajatshuvro** [comment]
Hello,
Sorry for the delay. The Jason output is in plain text format and not bgzipped. 

Please note that this tool is no longer being maintained. We have launched Illumina Connected Annotations built based on Nirvana. Please see: https://illumina.github.io/IlluminaConnectedAnnotationsDocumentation/ for details.
