### ISSUE TITLE
Illegal Instruction - Jasix.dll or netcoredeps issue

### ISSUE THREAD

**Issue by schreyers** [Illumina/Nirvana#128]
Heya :) Not sure if its an issue or a setting missed, but: 

After updating the BlockCompression to skip using AVX, the example test starts to run but then gives the Illegal Instruction error message. The stack trace points to the Jasix.dll (last thing called). 

This line might mean that netcoredeps needs adding? I can't see netcoredeps anywhere though 

openat(AT_FDCWD, "/opt/Nirvana/bin/Release/net6.0/netcoredeps/tls/x86_64/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

CMD line is:
```
dotnet Nirvana.dll -c /opt/Nirvana/Data/Cache/GRCh37/Both --sd /opt/Nirvana/Data/SupplementaryAnnotation/GRCh37 -r /opt/Nirvana/Data/References/Homo_sapiens.GRCh37.Nirvana.dat -i /home/tmp_annotation/HiSeq.10000.vcf.gz -o /home/tmp_annotation/HiSeq_test
```
Is there a step missed in the setup maybe? thanks

Output from cmd is:

```
---------------------------------------------------------------------------
Nirvana                                             (c) 2022 Illumina, Inc.
Stromberg, Roy, Platzer, Siddiqui, Ouyang, et al                     3.18.1
---------------------------------------------------------------------------

Initialization                                         Time     Positions/s
---------------------------------------------------------------------------
Cache                                               00:00:03.3
SA Position Scan                                    00:00:00.4       23,214

Reference                                Preload    Annotation   Variants/s
---------------------------------------------------------------------------
Illegal instruction
```

**Comment by schreyers** [comment]
Using VEP instead

**Comment by rajatshuvro** [comment]
Please note that this tool is no longer being maintained. We have launched Illumina Connected Annotations built based on Nirvana. Please see: https://illumina.github.io/IlluminaConnectedAnnotationsDocumentation/ for details.
