### ISSUE TITLE
Nirvana 2.0.1 throws exception on Ubuntu 17.10

### ISSUE THREAD

**Issue by dvav** [Illumina/Nirvana#13]
Hi,

I downloaded Nirvana 2.0.1 from the Releases page and tried to run it on Ubuntu 17.10 using Mono:

`mono <nirvana dir>/Nirvana.dll`

The software threw the following exception:

`Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Nirvana.Nirvana' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CommandLine.Utilities.CommandLineUtilities' threw an exception.
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at Nirvana.Nirvana..cctor () [0x00000] in <7a2bdc88de634e86a96d9a77cfdc60dd>:0 
   --- End of inner exception stack trace ---`

Release 1.6.2 works normally, though. Mono was installed using the following:
`sudo apt-get install mono-runtime mono-complete`.

Any ideas about how to resolve this problem?

Many thanks,
Dimitris

**Comment by haochenl** [comment]
Hi Dimitris,

The targeted framework for Nirvana 2.0.1 is dotnet core 2.0 (while it is dotnet core 1.1 for Nirvana 1.6.2). Maybe you can check if you need to update mono to support dotnet core 2.0. If not possible, you can always install dotnet core 2.0 to run Nirvana

**Comment by dvav** [comment]
Hi Haochen,

I can confirm that it works with dotnet core 2.0.3.

Many thanks for your prompt reply,
Dimitris
