### ISSUE TITLE
Options documentation

### ISSUE THREAD

**Issue by pablosolar** [Illumina/Nirvana#131]
Hi all!

From [3.19 version](https://illumina.github.io/NirvanaDocumentation/introduction/getting-started) I'm trying to find out information about the following options:

```
      --str <VALUE>          user provided STR annotation TSV file
      --vcf-info <VALUE>     additional vcf info field keys (comma separated)
                               desired in the output
      --vcf-sample-info <VALUE>
                             additional vcf format field keys (comma separated)
                                desired in the output
```

But here is no any detailed used more than that. Can you give some examples about how to use each one of them, restrictions, input format and so on?

Thank you in advance!

**Comment by rajatshuvro** [comment]
Hi @pablosolar ,
Please note that we have moved our documentation to https://illumina.github.io/IlluminaConnectedAnnotationsDocumentation/introduction/getting-started#the-illumina-connected-annotations-command-line

Having said that, I see the documentation gap. 

--str allows a  user to provide custom files for STR frequencies. You may check the file here for details
https://github.com/Illumina/Nirvana/tree/main/RepeatExpansions/Resources. 
--vcf-info allows you to pass fields from VCF info into the output json (e.g. --vcf-info IF1,IF2)
--vcf-sample-info allows you to pass on sample fields (e.g. --vcf-sample-info SF1,SF2)

Hope that helps.

**Comment by pablosolar** [comment]
Hey @rajatshuvro,

Thank you for the quick response. Clear now! Just one last question: does Nirvana validates these 3 inputs somehow? I mean, for example, in str the tsv format/columns, in vcf-info the field existence, ... and throws and error?
