### ISSUE TITLE
Bad help info in 3.18?

### ISSUE THREAD

**Issue by pablosolar** [Illumina/Nirvana#133]
Hello!

I'm using `v3.18.1` and I faced this issue when trying to use the `--sources, -s <VALUE>  annotation data sources to be used (comma separated list of supported tags)` so I want to understand:

```
Some problems were encountered when parsing the command line options:
  - ERROR: Found unknown command-line option(s): --sources, omim,gnomad
```

when running this command:

`dotnet /home/Nirvana/bin/Release/net6.0/Nirvana.dll -c Cache/GRCh37/Both --sd SupplementaryAnnotation/GRCh37 -r Homo_sapiens.GRCh37.Nirvana.dat -i NA12878.chr1.9009406.vcf -o out/NA12878_nirvana --sources omim,gnomad`

Logs shows this:
```

  Nirvana                                             (c) 2022 Illumina, Inc.
  Stromberg, Roy, Platzer, Siddiqui, Ouyang, et al                     3.18.1
  ---------------------------------------------------------------------------

  USAGE: dotnet Nirvana.dll -i <vcf path> -c <cache prefix> --sd <sa dir> -r <ref path> -o <base output filename>
  Annotates a set of variants

  OPTIONS:
        --cache, -c <prefix>   input cache prefix
        --in, -i <path>        input VCF path
        --out, -o <file path>  output file path
        --ref, -r <path>       input compressed reference sequence path
        --sd <directory>       input supplementary annotation directory
        --force-mt             forces to annotate mitochondrial variants
        --legacy-vids          enables support for legacy VIDs
        --enable-dq            report DQ from VCF samples field
        --str <VALUE>          user provided STR annotation TSV file
        --vcf-info <VALUE>     additional vcf info field keys (comma separated)
                                 desired in the output
        --vcf-sample-info <VALUE>
                               additional vcf format field keys (comma separated)
                                  desired in the output
        --help, -h             displays the help menu
        --version, -v          displays the version`


```

So, looking at this, `--sources, -s` is not supported. It is OK.

But my surprise came when if I use the `--enable-bidirectional-fusions` it works but this option is also missing from the info.

Is this an info error or what is going on there? Thank you in advance!

**Comment by rajatshuvro** [comment]
Hi @pablosolar ,
Please note that Nirvana is no longer supported. Please download newer versions from here: https://developer.illumina.com/illumina-connected-annotations

Best
Rajat
