### ISSUE TITLE
Nirvana 2.0.1 run test data on Ubuntu 16.04 error

### ISSUE THREAD

**Issue by yusmile0618** [Illumina/Nirvana#14]
Here is the error,can you help me figure out what's wrong with it?

$ dotnet bin/Release/netcoreapp2.0/Nirvana.dll -c Cache/24/GRCh37/Ensembl84 --sd GRCh37 -r References/5/Homo_sapiens.GRCh37.Nirvana.dat -i HiSeq.10000.vcf -o HiSeqtest
---------------------------------------------------------------------------
Nirvana                                             (c) 2017 Illumina, Inc.
Stromberg, Roy, Lajugie, Jiang, Li, and Kang                          2.0.1
---------------------------------------------------------------------------

ERROR: Unable to read beyond the end of the stream.

Stack trace:
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at VariantAnnotation.IO.ExtendedBinaryReader.ReadOptInt32() in /home/yu/Nirvana/VariantAnnotation/IO/ExtendedBinaryReader.cs:line 35
   at VariantAnnotation.SA.SaIndex.GetGlobalMajorAlleleInRefMinor(ExtendedBinaryReader reader) in /home/yu/Nirvana/VariantAnnotation/SA/SaIndex.cs:line 81
   at VariantAnnotation.SA.SaIndex.Read(Stream stream) in /home/yu/Nirvana/VariantAnnotation/SA/SaIndex.cs:line 64
   at VariantAnnotation.Providers.RefMinorProvider..ctor(List`1 supplementaryAnnotationDirectories) in /home/yuNirvana/VariantAnnotation/Providers/RefMinorProvider.cs:line 19
   at Nirvana.ProviderUtilities.GetRefMinorProvider(List`1 supplementaryAnnotationDirectories) in /home/yu/Nirvana/Nirvana/ProviderUtilities.cs:line 46
   at Nirvana.Nirvana.ProgramExecution() in /home/yu/Nirvana/Nirvana/Nirvana.cs:line 35
   at CommandLine.Builders.ConsoleAppErrors.Execute(Func`1 executeMethod) in /home/yu/Nirvana/CommandLine/Builders/ConsoleAppBuilder.cs:line 158

**Comment by MichaelStromberg** [comment]
Which version of the supplementary database are you using for Nirvana 2.0.1?

Nirvana 2.0.1 uses v40 of the supplementary database. You can download the newer versions here:
https://github.com/Illumina/Nirvana/wiki/Getting-Started

**Comment by yusmile0618** [comment]
@MichaelStromberg thanks, I use v40 supplementary database here's my Data dir below.

/home/yu/Nirvana/Data/
├── Cache
│   └── 24
│       ├── GRCh37
│       │   ├── Both84.polyphen.ndb
│       │   ├── Both84.sift.ndb
│       │   ├── Both84.transcripts.ndb
│       │   ├── Ensembl84.polyphen.ndb
│       │   ├── Ensembl84.sift.ndb
│       │   ├── Ensembl84.transcripts.ndb
│       │   ├── GRCh37_Ensembl_24.gff.gz
│       │   ├── GRCh37_RefSeq_24.gff.gz
│       │   ├── GRCh37_Regulatory_24.gff.gz
│       │   ├── RefSeq84.polyphen.ndb
│       │   ├── RefSeq84.sift.ndb
│       │   └── RefSeq84.transcripts.ndb
│       └── GRCh38
│           ├── Both84.polyphen.ndb
│           ├── Both84.sift.ndb
│           ├── Both84.transcripts.ndb
│           ├── Ensembl84.polyphen.ndb
│           ├── Ensembl84.sift.ndb
│           ├── Ensembl84.transcripts.ndb
│           ├── GRCh38_Ensembl_24.gff.gz
│           ├── GRCh38_RefSeq_24.gff.gz
│           ├── GRCh38_Regulatory_24.gff.gz
│           ├── RefSeq84.polyphen.ndb
│           ├── RefSeq84.sift.ndb
│           └── RefSeq84.transcripts.ndb
├── References
│   └── 5
│       ├── Homo_sapiens.GRCh37.Nirvana.dat
│       └── Homo_sapiens.GRCh38.Nirvana.dat
└── SupplementaryDatabase
    └── 40
        └── GRCh37
            ├── chr10.npd
            ├── chr10.nsa
            ├── chr10.nsa.idx
            ├── chr11.npd
            ├── chr11.nsa
            ├── chr11.nsa.idx
            ├── chr12.npd
            ├── chr12.nsa
            ├── chr12.nsa.idx
            ├── chr13.npd
            ├── chr13.nsa
            ├── chr13.nsa.idx
            ├── chr14.npd
            ├── chr14.nsa
            ├── chr14.nsa.idx
            ├── chr15.npd
            ├── chr15.nsa
            ├── chr15.nsa.idx
            ├── chr16.npd
            ├── chr16.nsa
            ├── chr16.nsa.idx
            ├── chr17.npd
            ├── chr17.nsa
            ├── chr17.nsa.idx
            ├── chr18.npd
            ├── chr18.nsa
            ├── chr18.nsa.idx
            ├── chr19.npd
            ├── chr19.nsa
            ├── chr19.nsa.idx
            ├── chr1.npd
            ├── chr1.nsa
            ├── chr1.nsa.idx
            ├── chr20.npd
            ├── chr20.nsa
            ├── chr20.nsa.idx
            ├── chr21.npd
            ├── chr21.nsa
            ├── chr21.nsa.idx
            ├── chr22.npd
            ├── chr22.nsa
            ├── chr22.nsa.idx
            ├── chr2.npd
            ├── chr2.nsa
            ├── chr2.nsa.idx
            ├── chr3.npd
            ├── chr3.nsa
            ├── chr3.nsa.idx
            ├── chr4.npd
            ├── chr4.nsa
            ├── chr4.nsa.idx
            ├── chr5.npd
            ├── chr5.nsa
            ├── chr5.nsa.idx
            ├── chr6.npd
            ├── chr6.nsa
            ├── chr6.nsa.idx
            ├── chr7.npd
            ├── chr7.nsa
            ├── chr7.nsa.idx
            ├── chr8.npd
            ├── chr8.nsa
            ├── chr8.nsa.idx
            ├── chr9.npd
            ├── chr9.nsa
            ├── chr9.nsa.idx
            ├── chrM.nsa
            ├── chrM.nsa.idx
            ├── chrMT.npd
            ├── chrX.npd
            ├── chrX.nsa
            ├── chrX.nsa.idx
            ├── chrY.npd
            ├── chrY.nsa
            ├── chrY.nsa.idx
            └── genePhenotypeMap.mim

9 directories, 102 files

**Comment by JFL9421** [comment]
Which version of Nirvana should be used for running data with Cache/26, References/5 and v44 supplementary database? Thanks!
