### ISSUE TITLE
Directly output JSON file, NOT .json.gz?

### ISSUE THREAD

**Issue by JasonYao81000** [Illumina/Nirvana#18]
In this issue: https://github.com/Illumina/Nirvana/issues/2
I can get a json file, but it will contain some console outputs.
Is there any way to hide console outputs and only generate JSON file?

Thanks

**Comment by haochenl** [comment]
This is fixed in Nirvana [2.0.8](https://github.com/Illumina/Nirvana/releases/tag/v2.0.8).

**Comment by MichaelStromberg** [comment]
Hi Jason,

We identified another issue related to stdin/stdout handling. We have addressed these issues in Nirvana 2.0.9. Let us know if that resolves your issues.

Best regards,
// Michael

**Comment by JasonYao81000** [comment]
Outputing JSON file directly works perfectly for me, thanks!
