### ISSUE TITLE
"latest" is not a tag number so the config script does not behave well

### ISSUE THREAD

**Issue by dbrami** [Illumina/Nirvana#21]
Hi all,
I made all the edits to the TestNirvana.sh as ncessary.
But when modifying the "NIRVANA_TAG" to the latest tag (in my case verifying it is 2.0.9), the script gave me the following error:
`$ bash ./TestNirvana.sh 
 _   _ _                             
| \ | (_)                            
|  \| |_ _ ____   ____ _ _ __   __ _ 
| . ` | | '__\ \ / / _` | '_ \ / _` |
| |\  | | |   \ V / (_| | | | | (_| |
|_| \_|_|_|    \_/ \__,_|_| |_|\__,_|

- downloading up to ~27 GB of data files in parallel (this will probably take a while)... 
finished.
- unpacking reference files... finished.
- unpacking cache files... finished.
- unpacking supplementary annotation GRCh37 files... finished.
Initialized empty Git repository in /mnt/acer2tb/dbrami/annotation/nirvana/.git/
remote: Counting objects: 11361, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11361 (delta 0), reused 10 (delta 0), pack-reused 11351
Receiving objects: 100% (11361/11361), 91.92 MiB | 4.66 MiB/s, done.
Resolving deltas: 100% (6860/6860), done.
From https://github.com/Illumina/Nirvana
 * [new branch]      develop    -> origin/develop
 * [new branch]      master     -> origin/master
 * [new tag]         v2.0.8     -> v2.0.8
 * [new tag]         v1.4.2     -> v1.4.2
 * [new tag]         v1.5.4     -> v1.5.4
 * [new tag]         v1.6.2     -> v1.6.2
 * [new tag]         v2.0.0     -> v2.0.0
 * [new tag]         v2.0.1     -> v2.0.1
 * [new tag]         v2.0.2     -> v2.0.2
 * [new tag]         v2.0.3     -> v2.0.3
 * [new tag]         v2.0.4     -> v2.0.4
 * [new tag]         v2.0.5     -> v2.0.5
 * [new tag]         v2.0.6     -> v2.0.6
 * [new tag]         v2.0.7     -> v2.0.7
error: pathspec 'v2.0.9' did not match any file(s) known to git.
./TestNirvana.sh: line 127: pushd: Nirvana: No such file or directory
`
I made a copy of the TestNirvana.sh script and replaced the file testing before download to touch (as files had been previously decompressed in previous attempt) and changed the NIRVANA_TAG to "master".
That seemed to have fixed my install and it ran successfully.

**Comment by MichaelStromberg** [comment]
Good find. We recently updated the TestNirvana.sh script to always extract the latest tag. Works much better now.
