### ISSUE TITLE
Source code of BlockCompression

### ISSUE THREAD

**Issue by fo40225** [Illumina/Nirvana#26]
According to https://github.com/Illumina/Nirvana/wiki/Dependencies

BlockCompression uses QuickLZ, the BlockCompression library should provide source code.

It can solve #15 #23.

**Comment by MichaelStromberg** [comment]
Excellent point! We have now moved our git repo for the BlockCompression library. Right now it handles Linux and Windows out of the box. We'll add Intel and M1-flavored MacOS Makefiles soon.

Here's the link: https://github.com/Illumina/BlockCompression
