### ISSUE TITLE
Nirvana JSON file formats (small variants) documentation

### ISSUE THREAD

**Issue by pablo-esteban** [Illumina/Nirvana#27]
The json file format documents contain a broken link in the description of the `vid` field. The description column only contains the text "Illumina Variant IDentifier" that links to https://confluence.illumina.com/display/PAT/VID which results in a page-not-found error.

Both Nirvana JSON file formats (small variants) files (1.5.4 and 1.6.2) in the [Output File Formats](https://github.com/Illumina/Nirvana/wiki/Design-Documents) have this issue (p9 and p7, respectively).

**Comment by MichaelStromberg** [comment]
Hi Pablo,

Thank you for the update. We're in the process of moving to a new documentation website where we can share that information more readily: https://illumina.github.io/NirvanaDocumentation/

The VID page is not on that site yet, but we'll add it this week.

**Comment by MichaelStromberg** [comment]
FYI: The new VID page is now up: https://illumina.github.io/NirvanaDocumentation/core-functionality/variant-ids
