### ISSUE TITLE
A Question about Consequences of Annotation

### ISSUE THREAD

**Issue by SamGLZ** [Illumina/Nirvana#30]
Hi Nirvana,

Thank you for the wonderful work!

I'm trying to figure out how Nirvana defined the consequence of a variant in the annotation process, for example, NMD_transcript_variant or transcript_ablation. I've read some code of this project. However, I'm not very familiar with C# and it's not easy for me to find out which files are related to these definitions. 

Sorry for bothering you, but it would be nice if you can show me where the definitions from or which files relate to this question so that I can read them by myself. Thank you!

Sam

**Comment by rajatshuvro** [comment]
Hello Sam,
Thank you for using Nirvana. We follow Sequence Ontology definitions. For example, you can find the definition for NMD_transcript_variant here http://www.sequenceontology.org/browser/current_release/term/SO:0001621. You can search for terms on their website too.  

Hope that helps
Rajat
