### ISSUE TITLE
Splice site predictions

### ISSUE THREAD

**Issue by elly1502** [Illumina/Nirvana#32]
Hi,
Are there any plans to incorporate splice site predictions into Nirvana?

Thanks

**Comment by rajatshuvro** [comment]
Hello,
We do have splice predictions from SpliceAI in the latest Nirvana. Please search for the keyword "spliceAI" in our JSON output. But please be aware that SpliceAI might soon be removed due to licensing issues. Till that happens, please enjoy it.

Thanks
Rajat
