### ISSUE TITLE
Usage manual/guide

### ISSUE THREAD

**Issue by jerryliu2005** [Illumina/Nirvana#37]
I'm looking for documentation of how to do SV (CNV) annotation using Nirvana. Our use case is large-scale variant annotation on both WGS and WES VCFs. Your input/advice would be highly appreciated. Is Hail the only way to go?

Thanks,
Jerry

**Comment by rajatshuvro** [comment]
Hi Jerry,
SV/CNV annotations are handled seamlessly in Nirvana. You run the same command line as with a small variant file. If you have a large number of variants, your output might be large and that will also mean a longer execution time. In such cases, we recommend that you tabix the file and create smaller ones (say one pre chromosome or even smaller) and run them in parallel.

Hope that helps
Thanks
Rajat
