### ISSUE TITLE
Some Undocumented JSON Fields

### ISSUE THREAD

**Issue by johnc1231** [Illumina/Nirvana#4]
So far, I've encountered three fields in Nirvana output that were not listed in the pdf detailing the format. They are as follows:

header.genomeAssembly
variants.transcripts.ensembl.bioType
variants.regulatoryRegions.type

Just thought I'd let you know.

**Comment by MichaelStromberg** [comment]
Thanks!

We're in the process of updating all of our documentation. We'll update the JSON schema PDF today with the latest version. While that's fine for the short term, we're also having broader discussions about moving our documentation to a public location to prevent the information from becoming outdated.

**Comment by MichaelStromberg** [comment]
Thanks for the heads up! This has been reflected in the updated documentation.
