### ISSUE TITLE
Got Error when using nirvana to do annotate

### ISSUE THREAD

**Issue by LvLH** [Illumina/Nirvana#40]
# command
`
dotnet.exe ../bin/Release/netcoreapp2.1/Nirvana.dll -c ../Data/Cache/GRCh37/Both -r ../Data/References/Homo_sapiens.GRCh37.Nirvana.dat -i sample1.vcf -o sample1.annotated
`
I got Error below:
```
---------------------------------------------------------------------------
Nirvana                                             (c) 2020 Illumina, Inc.
Stromberg, Roy, Lajugie, Jiang, Li, and Kang                         3.10.1
---------------------------------------------------------------------------

Initialization                                         Time     Positions/s
---------------------------------------------------------------------------
Cache                                               00:00:01.5

Reference                                Preload    Annotation   Variants/s
---------------------------------------------------------------------------

ERROR: Expected 7443623 bytes from the block, but received only 2449027 bytes.
```

Hope get your help. Thanks.

**Comment by LvLH** [comment]
I solved this problem, for my downloading files with some truncated. Such as " Both.sift.ndb".
Sorry to trouble.

**Comment by MichaelStromberg** [comment]
Glad to hear that you found the root cause! In the Downloader, we try to provide additional information about which files may have been truncated in case you get a partial download. The good news is that the Downloader can fix those issues and only download the files that have issues or that are out-of-date.
