### ISSUE TITLE
Truncated supplementary data source files

### ISSUE THREAD

**Issue by junyanzho** [Illumina/Nirvana#42]
I try to annotate variants of VCF( including 3589 SNPs), encounter ERROR as below:

---------------------------------------------------------------------------
Nirvana                                             (c) 2020 Illumina, Inc.
Stromberg, Roy, Lajugie, Jiang, Li, and Kang             3.13.0-0-ga57e78a7
---------------------------------------------------------------------------

Initialization                                         Time     Positions/s
---------------------------------------------------------------------------
Cache                                               00:00:01.9
SA Position Scan                                    00:00:00.9        3,710

Reference                                Preload    Annotation   Variants/s
---------------------------------------------------------------------------
chr1                                    00:00:10.6  00:00:03.7          114
chr2                                    00:00:09.7  00:00:03.2           82
chr3                                    00:00:08.0  00:00:02.7           72
chr4                                    00:00:03.6  00:00:02.3           73

ERROR: Unable to read beyond the end of the stream.

Stack trace:
   at System.IO.BinaryReader.ReadByte()
   at IO.ExtendedBinaryReader.ReadOptInt32() in D:\Projects\Nirvana_3.13\IO\ExtendedBinaryReader.cs:line 46
   at VariantAnnotation.NSA.NsaBlock.Read(ExtendedBinaryReader reader) in D:\Projects\Nirvana_3.13\VariantAnnotation\NSA\NsaBlock.cs:line 41
   at VariantAnnotation.NSA.NsaReader.PreLoad(IChromosome chrom, List`1 positions) in D:\Projects\Nirvana_3.13\VariantAnnotation\NSA\NsaReader.cs:line 91
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

Then, I split and annotate variants by chromosome. Annotation are completed with chromosome 1-4, annotation on other chromosomes(5-22, X) also failed with above ERROR.

 Could you help me figure out what is wrong?

Thanks!

**Comment by MichaelStromberg** [comment]
Hi there, 

This usually happens if one of the Supplementary Annotation data sources was truncated. One way of fixing this is to re-run the Downloader using the same output directory as you used before. This way, Nirvana will repair any truncated files that it finds.

Let me know if that works for you.

Besides that, this is reminding me that it would be incredibly helpful if Nirvana could indicate which Supplementary Annotation file was truncated (i.e. the one that triggered the `ERROR: Unable to read beyond the end of the stream.` exception.

**Comment by junyanzho** [comment]
We try to re-run downloader and test. It's OK now.
Thanks for your help.

**Comment by MichaelStromberg** [comment]
Awesome! We're going to add some better debugging text to our error messages to make that easier in the future.

For curiosity, what do you think led to the truncated file? Did you run out of disk space or do you think there was an issue with the network connectivity? We're trying to identify how people are getting truncated files in an effort to improve our workflow.

**Comment by junyanzho** [comment]
In my situation, it was caused by network connection.
