### ISSUE TITLE
Possible error / point of confusion around canonical variant IDs in docs

### ISSUE THREAD

**Issue by edawson** [Illumina/Nirvana#44]
Hi,

   When reviewing the docs, I noticed I had some confusion around an example in the [canonical variant id portion](https://illumina.github.io/NirvanaDocumentation/core-functionality/variant-ids).

The final variant listed in the docs appears to have an incorrect reference allele in the variant ID of the second allele:
```
chr1    66572   .   GTA G,GTACTATATATTATA   45.45   PASS    .
##Format: chromosome—position—reference allele—alternate allele
    1-66572-GTA-G
    1-66572-G-GTACTATATATTA
```

Did I perhaps not left-align + trim this correctly in my brain? It looks to me like this variant id should read `1-66572-GTA-GTACTATATATTA`. If it were trimmed, I think it might read `1-66575-A-ACTATATATTA`. Any clarification y'all might have on this would be great - thanks!

**Comment by MichaelStromberg** [comment]
Hi Eric,

That does look odd. I'll look into this today.

**Comment by MichaelStromberg** [comment]
Here's a visual depiction of the alignment process. Notice that we're really just changing the location of the genomic `TA` alleles.

![](https://gist.githubusercontent.com/MichaelStromberg/9744715336166141b32da5709efc7d1c/raw/780f95d5016c4ad5479cb93f7d1d26e985ccb4e6/Alignment.svg)

**Comment by edawson** [comment]
Ah, I see. This was very helpful and a really interesting one once you showed the ref bases - thanks!!
