### ISSUE TITLE
Docker images for Nirvana 3.14+

### ISSUE THREAD

**Issue by LeeTL1220** [Illumina/Nirvana#46]
The latest version of Nirvana docker image is 3.9.1, which has diverged from the documentation.  

Are you planning to release later versions of Nirvana in a docker image?  On dockerhub?

Feel free to close this issue once responding.

**Comment by MichaelStromberg** [comment]
Hi Lee,

In the past we haven't made regular releases on DockerHub, just on an ad hoc basis. I'll go ahead and create one for Nirvana 3.14 later today.

**Comment by LeeTL1220** [comment]
@MichaelStromberg Thanks for doing that!

I do not see a 3.14 tag available.  I just want to confirm that I am not missing anything...

(https://hub.docker.com/r/annotation/nirvana/tags?page=1&ordering=last_updated)

**Comment by MichaelStromberg** [comment]
Hi Lee,

Sorry about that. Here you go: `docker pull annotation/nirvana:3.14`

In case you ever want to roll your own Nirvana Docker container, here's my Dockerfile:
https://github.com/MichaelStromberg-Illumina/DotNetMisc/blob/master/Dockerfiles/Nirvana/Dockerfile

**Comment by LeeTL1220** [comment]
Thank you so much!

**Comment by LeeTL1220** [comment]
Minor issues I noticed:

The v3.14 docker image generates discordant version number:
```
    "annotator": "Nirvana 3.13.0",
```

The v3.9.1 VEP datasource is newer than the v3.14 VEP datasource:
3.9.1:
```
    "dataVersion": "91.26.57",
.......
{
        "name": "VEP",
        "version": "91",
        "description": "BothRefSeqAndEnsembl",
        "releaseDate": "2018-03-05"
      }
...
```

v3.14
```
    "dataVersion": "91.27.61",
....
      {
        "name": "VEP",
        "version": "91",
        "description": "BothRefSeqAndEnsembl",
        "releaseDate": "2017-12-18"
      },
...
```

**Comment by natbutter** [comment]
> Hi Lee,
> 
> Sorry about that. Here you go: `docker pull annotation/nirvana:3.14`
> 
> In case you ever want to roll your own Nirvana Docker container, here's my Dockerfile: https://github.com/MichaelStromberg-Illumina/DotNetMisc/blob/master/Dockerfiles/Nirvana/Dockerfile

Any chance that Dockerfile is still available somewhere?  Looks like this may have been a private repo? Cheers.
