### ISSUE TITLE
NIRVANA output missing genes.hgncid

### ISSUE THREAD

**Issue by LeeTL1220** [Illumina/Nirvana#48]
Version: 3.14 from docker image.
Reference: hg38
Updated datasources using the Download tool in NIRVANA?  Yes, from the same docker image (tag 3.14).

According to the documentation, the NIRVANA output should have a genes.hgncid field (the HGNC ID number, not gene symbol).  This is not the geneId field, which is based on NCBI.  

```
"genes":[
   {
      "name":"MSH6",
      "hgncId":7329,
...
```

(Above is a snippet from https://illumina.github.io/NirvanaDocumentation/file-formats/nirvana-json-file-format#genes)

However, in my output no gene has this.  E.g. 
```
"genes": [
    {
      "name": "AJAP1",
      "omim": [
        {
          "mimNumber": 610972,
          "geneName": "Adherens junction-associated protein 1"
        }
      ],
      "gnomAD": {
        "pLi": 0.995,
        "pRec": 0.00531,
        "pNull": 5.54e-07,
        "synZ": 0.163,
        "misZ": 0.936,
        "loeuf": 0.192
      }
    },
...
```
I do not see a hgncid field in any part of the output.

Thanks for any help.

**Comment by LeeTL1220** [comment]
I thought I would ping, just to ask whether this was going to be corrected in the next version of NIRVANA or whether the documentation was going to be updated to match the actual output.  Or whether I am just missing something obvious?  Any help is appreciated.

**Comment by snalty** [comment]
I would also like some clarity on this.

**Comment by rajatshuvro** [comment]
Hi @snalty , @LeeTL1220 ,
Please follow the instructions here (https://illumina.github.io/IlluminaConnectedAnnotationsDocumentation/introduction/getting-started) to get the latest version of Nirvana (now called Illumina Connected Annotations) and let us know if the problem persists.

Thanks

**Comment by snalty** [comment]
Hi @rajatshuvro,

I did find this through my own searches and this is great thanks, works perfectly and shows the hgncId in the genes section of the json.

BW
