### ISSUE TITLE
SAUtils conflicting entries in custom annotation

### ISSUE THREAD

**Issue by IvantheDugtrio** [Illumina/Nirvana#55]
[2021-06-10_classification_database-IAD.txt](https://github.com/Illumina/Nirvana/files/7009907/2021-06-10_classification_database-IAD.txt)
I'm having an issue creating a custom annotation with SAUtils 3.16.1-0, where I keep getting an error stating the following:
`conflicting entries for items at chr1:6257785 for alleles > T`
Deleting the notes column changes the error to a different coordinate, however neither coordinate exist in the file. Is there a parsing error with this file? See the attached.

**Comment by rajatshuvro** [comment]
Hi @IvantheDugtrio ,
I don't see any attachments. 
This error usually triggers when you have conflicting annoation values for the same variant. I can be sure once I see the file.

Thanks
Rajat

**Comment by rajatshuvro** [comment]
This looks like a bug indeed. I am investigating this issue.

**Comment by rajatshuvro** [comment]
Hi @IvantheDugtrio ,
I found the issue. If you look at the range chr1:6,257,784-6,257,792 on ucsc genome browser, you will see that it is all Ts. So an insertion of T at 6257793 can be left shifted to an insertion of T at 6257785. In other words, chr1-6257792-T-TT is equivalent to chr1-6257784-C-CT. That is why, our SAUtils tool is complaining. Please remove one of them and it should work fine.

Hope this was useful.

Regards
Rajat

**Comment by IvantheDugtrio** [comment]
Hi @rajatshuvro ,

Thanks for the help! I cleaned up the annotation file and it imports successfully now. 

Thanks,
Ivan
