### ISSUE TITLE
Nirvana_UGA.tsv file?

### ISSUE THREAD

**Issue by ceftriaxoneBGD** [Illumina/Nirvana#58]
Dear developers,

How can I get access to the new version of this file? I am trying to insert some custom gene annotations, but have plenty of errors due to (I assume) outaded version of the uga.tsv file we have.

Thank you in advance.
Kind regards,
Ivan

**Comment by rajatshuvro** [comment]
Hi Ivan,
You can download the UGA file from here https://nirvana-annotations.s3.us-west-2.amazonaws.com/ab0cf104f39708eabd07b8cb67e149ba-Cache/27/UGA.tsv.gz. 

Thanks
Rajat
