### ISSUE TITLE
I'd like to use the latest version of gnomAD or at least version 3.0.

### ISSUE THREAD

**Issue by RoriCremer** [Illumina/Nirvana#64]
The documentation says the following:

>For GRCh38, Nirvana currently uses gnomAD version 3.0 which doesn't contain the exomes data. Therefore, only genomes data are presented in the output.

I'm currently using GRCh38, but all I'm seeing is 2.1

<img width="692" alt="Screen Shot 2021-10-29 at 4 20 02 PM" src="https://user-images.githubusercontent.com/6863459/139497200-d120e9b0-81d3-4673-8d82-6d49c5b3089b.png">

I'd like to use the latest version of gnomAD or at least version 3.0.

**Comment by rajatshuvro** [comment]
Hello @RoriCremer ,
We have updated to 3.1.2. Please run the downloader again and let us know if you don't see it.

Best
Rajat
