### ISSUE TITLE
Error creating custom gene file format

### ISSUE THREAD

**Issue by anleopa** [Illumina/Nirvana#66]
I am trying to create a custom annotation for genes by following the instruction described in https://illumina.github.io/NirvanaDocumentation/file-formats/custom-annotations/

Nevertheless, when I try to convert the example file (MyDatSource5.tsv) to Nirvana format using the command 

dotnet bin/Release/netcoreapp3.1/SAUtils.dll customvar -r Data/References/Homo_sapiens.GRCh38.Nirvana.dat -i MyDataSource5.tsv -o CA

I have the following error: Unexpected header tag observed

No details about the error are provided.

**Comment by rajatshuvro** [comment]
for gene CA building please use the CustomGene command and not CustomVar.
