### ISSUE TITLE
JSON schema for Nirvana output?

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [Illumina/Nirvana#69]
The header section mentions the `schemaVersion`, but I cannot seem to find the actual schema that the Nirvana output adheres to. Is the JSON schema available somewhere?

**Comment by rajatshuvro** [comment]
Unfortunately, we don't have the JSON schema anywhere. schemaVersion refers to https://json-schema.org/draft-06/json-schema-release-notes.html.
