### ISSUE TITLE
New JSON documentation does not agree with output 

### ISSUE THREAD

**Issue by johnc1231** [Illumina/Nirvana#7]
In the new JSON documentation https://github.com/Illumina/Nirvana/wiki/Nirvana-JSON-schema-(small-variants)#ExAC the listed schema does not agree with the schema on the PDF. The output I get from running Nirvana seems to be a combination of the PDF and new docs output as well. 

The new documentation claims their is an exac and 1kg struct containing the relevant data for each of those things. When I run Nirvana, I still get all the pdf style "oneKgAfr", "oneKgAmr", annotations. On the other hand, the PDF does not mention of this OMIM stuff that's in the new documentation, and I am seeing that output in the output file.

**Comment by yujiang02** [comment]
Sorry, this document is for our new version, which recently released in out enterprise github. We will sync these changes to this public github very soon.

**Comment by johnc1231** [comment]
Any idea when they will be synced?

**Comment by MichaelStromberg** [comment]
Hi John,

The new documentation is now in place!
