### ISSUE TITLE
How to update GRCh38 databases

### ISSUE THREAD

**Issue by geocarvalho** [Illumina/Nirvana#70]
Hello team, thank you for your work here.
I'm using Nirvana `v.3.17.0` and GRCh38 databases
```
$ bin/Release/netcoreapp3.1/Nirvana.dll --version
Nirvana 3.17.0 Cache version: 27, Supplementary annotation version: 63, Reference version: 7
```

The VEP database is quite old:
```
{
        "name": "VEP",
        "version": "91",
        "description": "BothRefSeqAndEnsembl",
        "releaseDate": "2017-12-18"
}
```

There is a new database for download or any way I could update it myself?

Best,
George.

**Comment by rajatshuvro** [comment]
Hello @geocarvalho ,
We are currently working on updating RefSeq to a recent release. Our 3.2.6 already has that. But please be advised that the Supplementary annotations for 3.2.6 are quite old.

**Comment by geocarvalho** [comment]
Thank you @rajatshuvro, but I couldn't find the links to download the GRCh38 databases for `v3.2.6`, there is a link for that?
Another thing is if there is any possibility of updating or adding new databases myself?
