### ISSUE TITLE
How can I add my own database into Nirvana databases

### ISSUE THREAD

**Issue by kpalanikannan** [Illumina/Nirvana#71]
I have my internal database for variants. I have it as CSV formatted table. Chr position(s) in first three columns as same as BED format and annotations from 4th column to 8th column. Please help me on the procedure to incorporate custom own databases into NIRVANA code.

**Comment by rajatshuvro** [comment]
Hi @kpalanikannan ,
Thank you for using Nirvana. Please find instructions to create custom databases here: https://illumina.github.io/NirvanaDocumentation/file-formats/custom-annotations/

Best
Rajat
