### ISSUE TITLE
Trying out Nirvana

### ISSUE THREAD

**Issue by deepakunni3** [Illumina/Nirvana#8]
I wanted to test out Nirvana for variant annotation.

I tried out the `test_nirvana.sh` script to setup Nirvana on Mac OS X, but it looks like the download links for the datasets used by the script itself are not publicly accessible.

Any chance I can access these files as-is?

**Comment by MichaelStromberg** [comment]
Hi Deepak,

It looks like Illumina changed the setting on our shared links. We're in the process of moving all the data to S3, so we'll update the links once everything has been uploaded. Sorry!

// Michael

**Comment by deepakunni3** [comment]
@MichaelStromberg Thanks for responding so quick.

No worries! :)
I can wait for the updated links.

**Comment by MichaelStromberg** [comment]
Hi Deepak,

Sorry for the delay. We have now migrated everything over to S3. Please download the updated [TestNirvana.sh](https://raw.githubusercontent.com/wiki/Illumina/Nirvana/scripts/TestNirvana.sh) script and give it another go.

Best regards,

// Michael

**Comment by deepakunni3** [comment]
Thanks!
