### ISSUE TITLE
Latest release (3.18.1) does not include Downloader

### ISSUE THREAD

**Issue by olingerc** [Illumina/Nirvana#81]
When comparing the releases 3.18.0 and 3.18.1 assets that can be downloaded from the release page, the latest release does not contain the files starting with "Downloader". Also, "Phantom" files are not included.

**Comment by rajatshuvro** [comment]
Thank you for reporting the issue @olingerc . I can confirm that the Downloader.dll is missing. We are working to fix it. In the meantime, please feel free to download the latest main branch and compile it- that should produce the Downloader.dll for you.

**Comment by rajatshuvro** [comment]
I have added the Downloader.dll to the zip files. Please let me know if there are any more issues.

Thanks
Rajat

**Comment by olingerc** [comment]
The release page assets does not yet list the finished build. Building from source works but might not be possible for everyone.
![image](https://user-images.githubusercontent.com/5046645/175064160-6df228b7-a3b6-48ab-88ae-361c6fc90f02.png)

**Comment by rajatshuvro** [comment]
Sorry about that. It has been fixed.

**Comment by olingerc** [comment]
Thanks @rajatshuvro !
