### ISSUE TITLE
[Feature Request]  Docker image for latest NIRVANA version

### ISSUE THREAD

**Issue by LeeTL1220** [Illumina/Nirvana#84]
Can you create a docker image and tag (in [dockerhub](https://hub.docker.com/r/annotation/nirvana/tags?page=1&ordering=last_updated)) for the latest version of NIRVANA?

**Comment by LeeTL1220** [comment]
(With the latest datasources, esp. gnomAD 3.x)

**Comment by rajatshuvro** [comment]
Given the large volume of data needed to run Nirvana (about 20GB), creating a performant docker image is not feasible. Therefore, we have chosen not to publish docker images for Nirvana.

**Comment by LeeTL1220** [comment]
Huh?  The docker image for NIRVANA should not include datasources -- those get mounted externally.  The image for 3.14 didn't include the datasources and it was quite performant.  Why would 3.18 be any different?

I just meant that the Downloader in the docker image should download the latest version of the datasources.  

@rajatshuvro

**Comment by LeeTL1220** [comment]
(Not to beat a dead horse but...) 

To give you an idea of scale, we used NIRVANA 3.14 in a docker image (that you provided) to annotate >700M variants for our 98k sample 30x WGS joint callset.  NIRVANA was performant.

https://www.researchallofus.org/
