### ISSUE TITLE
Looking for the within-callset AC, AN, AF for multi-sample VCF 

### ISSUE THREAD

**Issue by bw2** [Illumina/Nirvana#86]
Hi, thank you for developing Nirvana. 
I have a joint-called VCF with 1000+ samples and would like to know the AC, AF, AN, and HC of each _variant_  based on the samples contained in the VCF. 
I'm wondering if there's a way to get this info from Nirvana output without having to compute it using the "genotypes" list.

**Comment by rajatshuvro** [comment]
Hello @bw2 ,
Thank you for using Nirvana. Unfortunately, Nirvana has no functionality to compute any of the fields you mentioned. 

Best
Rajat
