### ISSUE TITLE
Open reading frame in MNVs

### ISSUE THREAD

**Issue by b-math** [Illumina/Nirvana#88]
Dear NIRVANA development team,
we are currently validating a somatic WES pipeline using the DRAGEN software and are planning to use NIRVANA for MNV detection.
According to the documentation, seed codons are defined as codons affected by multiple SNVs. Adjacent SNVs are combined to seed codons:
[https://illumina.github.io/NirvanaDocumentation/core-functionality/mnv-recomposition](https://illumina.github.io/NirvanaDocumentation/core-functionality/mnv-recomposition)

However, when testing on our files, we observed that in some cases not all adjacent SNVs were combined as a single MNV, even if they were phased together.
In the following example three cophased and adjacent variants were present (vcf input shown in **bold**, cophased variant by NIRVANA in _italics_). NIRVANA only combined the latter two into a MNV.
**chr14	38092025	.	G	C	.	PASS
chr14	38092026	.	A	T	.	PASS**
_chr14	38092026	.	AG	TC	.	PASS_
**chr14	38092027	.	G	C	.	PASS**

See attached an extract of the [original vcf file](https://github.com/Illumina/Nirvana/files/9488502/hard-filtered.vcf.txt) and the [NIRVANA output](https://github.com/Illumina/Nirvana/files/9488498/nirvana_output.json.txt).

We found out that the latter two bases form a codon in the open reading frame. **Does NIRVANA thus only output MNPs affecting the protein output?** Or was it just coincidence in our example?

Thank you very much for your time

Best regards,
Barbara

P.S: Do you know whether there is an option to update NIRVANA on the DRAGEN server? We are using DRAGEN Bio-IT 3.10, which was shipped with NIRVANA 3.16

**Comment by rajatshuvro** [comment]
Hi @b-math ,
You are correct, Nirvana only creates MNVs if the SNVs are in the same codon. So, what you see is the expected behavior.

You may be sad to hear that we are dis-continuing the MNV recomposition support in Nirvana. Dragen will support MNV calling from now and that is why we have decided to remove that support from Nirvana. So, I would recommend not to standardize on Nirvana's MNV calling.

Unfortunately, there is no option to update Nirvana in Dragen servers unless you update the Dragen release. 

Regards
Rajat

**Comment by b-math** [comment]
Hi @rajatshuvro,

thank you very much for your answer. Great to hear that NIRVANA only creates MNVs if the SNVs are in the same codon.

Could you please clarify which DRAGEN Bio-IT versions (v3.10, v4) support MNV detection? We did not find this information in the Bio-IT online documentation.

Additionally, do you know by chance why DRAGEN v3.10 (released March 2022) was shipped with NIRVANA 3.16.1-0-gd410c14, although NIRVANA 3.17 was already released (October 2021).

Best regards,
Barbara

**Comment by b-math** [comment]
Dear all,

I wanted to give an update, in case somebody else is interested in the topic.

We were in contact with illumina TechSupport and in brief they gave us the following answers:

- MNV recomposition in DRAGEN will be done with the Combine [Phased Variants functionality](https://support-docs.illumina.com/SW/DRAGEN_v310/Content/SW/DRAGEN/PhasingPhasedVariants_fDG.htm). In contrast to NIRVANA, it combines variants regardless of the codons, but within a given distance.
- DRAGEN was shipped with Nirvana 3.16.1, since this is the most up-to date version integrated. 3.17 and 3.18 have been relatively minor updates and were not integrated in DRAGEN
- It is possible to install Nirvana as standalone tool, but this version does not have access to COSMIC because of licensing restrictions

Best regards,
Barbara
