### ISSUE TITLE
where is the Nirvana_UGA.tsv file

### ISSUE THREAD

**Issue by vaksmaz** [Illumina/Nirvana#89]
I am running the Nirvana custom annotation. I can run the variant level data easily however I am having issues with gene level data. 
I need the Nirvana_UGA.tsv file, and if you have any more instructions then what is in the manual.

**Comment by rajatshuvro** [comment]
Hi @vaksmaz ,
sorry for the late response. You can find the UGA file here: https://nirvana-annotations.s3.us-west-2.amazonaws.com/ab0cf104f39708eabd07b8cb67e149ba-Cache/27/UGA.tsv.gz.

Best
Rajat
