### ISSUE TITLE
How to update dbsnp version?

### ISSUE THREAD

**Issue by Griffan** [Illumina/Nirvana#98]
Currently, the downloader will download dbsnp_155 files, is there any plan to update the version? Or how can I manually edit this setting? Thanks!

**Comment by rajatshuvro** [comment]
Currently the latest version of dbSNP we support is 155. At the moment, there is no way to simply configure the downloader to get a more later version. But you can use our SAUtils tool (https://illumina.github.io/NirvanaDocumentation/utilities/sautils) to generate a more later version of dbSNP. The same is true for any other data sources. Please let me know if you need additional help using SAUtils.

Thanks
Rajat
